// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class AircraftSeat
    {
        public int IdAircraftSeat { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int IdBooking { get; set; }
        public string PassengerLastName { get; set; }
        public string PassengerFirstName { get; set; }
        public int IdFlight { get; set; }

        public virtual Booking IdBookingNavigation { get; set; }
        public virtual Flight IdFlightNavigation { get; set; }
    }
}