// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class Booking
    {
        public Booking()
        {
            AircraftSeats = new HashSet<AircraftSeat>();
        }

        public int IdBooking { get; set; }
        public int IdFlight { get; set; }
        public int IdClient { get; set; }
        public double BookingAmount { get; set; }

        public virtual Client IdClientNavigation { get; set; }
        public virtual Flight IdFlightNavigation { get; set; }
        public virtual ICollection<AircraftSeat> AircraftSeats { get; set; }
    }
}