// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class MembershipType
    {
        public MembershipType()
        {
            Clients = new HashSet<Client>();
        }

        public int IdMemberShipType { get; set; }
        public string Name { get; set; }
        public double DiscountFactor { get; set; }

        public virtual ICollection<Client> Clients { get; set; }
    }
}