// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class Planet
    {
        public Planet()
        {
            Airports = new HashSet<Airport>();
        }

        public int IdPlanet { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Airport> Airports { get; set; } = null;
    }
}