// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Temp.Data
{
    public partial class Airport
    {
        public Airport()
        {
            ItineraryIdAirport1Navigations = new HashSet<Itinerary>();
            ItineraryIdAirport2Navigations = new HashSet<Itinerary>();
        }

        public int IdAirport { get; set; }
        public string Name { get; set; }
        public int IdPlanet { get; set; }

        public virtual Planet IdPlanetNavigation { get; set; }
        public virtual ICollection<Itinerary> ItineraryIdAirport1Navigations { get; set; }
        public virtual ICollection<Itinerary> ItineraryIdAirport2Navigations { get; set; }
    }
}