// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Temp.Data
{
    public partial class Booking
    {
        public int IdBooking { get; set; }
        public int IdFlight { get; set; }
        public int IdClient { get; set; }
        public int NbSeats { get; set; }

        public virtual Client IdClientNavigation { get; set; }
        public virtual Flight IdFlightNavigation { get; set; }
    }
}