// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Temp.Data
{
    public partial class Flight
    {
        public Flight()
        {
            Bookings = new HashSet<Booking>();
        }

        public int IdFlight { get; set; }
        public int FlightStatus { get; set; }
        public int IdAircraft { get; set; }
        public double Price { get; set; }
        public int IdItinerary { get; set; }
        public DateTime DepartureTime { get; set; }
        public DateTime ArrivalTime { get; set; }
        public int RemainingSeats { get; set; }

        public virtual Aircraft IdAircraftNavigation { get; set; }
        public virtual Itinerary IdItineraryNavigation { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}