// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Temp.Data
{
    public partial class User
    {
        public User()
        {
            Clients = new HashSet<Client>();
        }

        public int IdUser { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public bool VerifiedEmail { get; set; }
        public int IdRole { get; set; }
        public string IdUserAuth0 { get; set; }

        public virtual Role IdRoleNavigation { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
    }
}